### ISSUE TITLE
Something wrong in code not sure what

### ISSUE THREAD

**Issue by temppase** [temppase/ML_test#1]
Will open interface but doesn't print anything.

**Comment by temppase** [comment]
I have tried to fix problem different ways but haven't yet found final error. It seems that it won't print even the first parameter what I use in test purpose.

**Comment by pplonski** [comment]
Please add a new cell below YAML cell with following code:

```python
p_year = 2019
t_size = 0.2
# all variables from YAML ...
```

Please keep only YAML vvaariables in this cell.

**Comment by temppase** [comment]
Aargh I forgot that... sorry and thanks lot I believe that this was missing part.

**Comment by temppase** [comment]
Yes now it works thanks a lot
